### ISSUE TITLE
Merge the two repos

### ISSUE THREAD

**Issue by phy25** [entalent/BIT_NetCheckin2#6]
What's the diffenence between entalent/BIT_NetCheckIn and entalent/BIT_NetCheckIn2? Why not make them into one repo (maybe in different branches)?

**Comment by LangleyChang** [comment]
Hello!
Because of a mess of login mechanism, entalent/BIT_NetCheckIn is no longer updated and supported. As you can see in entalent/BIT_NetCheckin2 , we have to send two different http request to different URLs once for we have no idea which attempt works.Without official support, we abandoned 1st version and start with the very begin again.

Thanks for your proposal.

**Comment by phy25** [comment]
OK... I'll close this.
